# Generated by Django 4.2.3 on 2023-12-12 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_alter_products_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='slug',
        ),
    ]
